"""Add the enumeration classes for project, registration, and volunteer record

Revision ID: 23749350217c
Revises: 3a335c0d6423
Create Date: 2025-12-17 21:46:02.437734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23749350217c'
down_revision = '3a335c0d6423'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registration', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_registration_user_project', ['user_id', 'project_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registration', schema=None) as batch_op:
        batch_op.drop_constraint('uq_registration_user_project', type_='unique')

    # ### end Alembic commands ###
