"""drop badge, badge_user, notification, system_settings tables

Revision ID: 3a335c0d6423
Revises: a1b2c3d4e5f6
Create Date: 2025-12-15 15:24:21.315713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a335c0d6423'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comment_parent_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comment_parent_id'), ['parent_id'], unique=False)

    # ### end Alembic commands ###
